### ISSUE TITLE
Skype Classic Version

### ISSUE THREAD

**Issue by cycl0ne** [cairoshell/cairoshell#168] opened 2018-07-07 07:04 UTC
**Describe the bug**
Skype wont respnd to left mouseclick anymore (doublick on name does not open message box, lclick on minimize window doesnt work, close doesnt work anymore etc.)

**Steps to reproduce**
1.  Use Win10 Pro
2.  Use Cairo Desktop
3.  Use Skype Classic Version

**Expected behavior**
Doubleclick on a name opens the message box. left click on the "minimize" buttons makes the window smaller, etc.

**System information:**
 - Windows version: Windows Pro 10
 - Cairo version: Latest
 - 32-bit or 64-bit:  64 Bit
 - In Cairo Settings > Advanced, is Cairo set as shell?:  Windows Explorer is set as the Shell

Problem solves:
Close and reopen Skype. But after a time, it wont work anymore.

**Comment by cycl0ne** [comment] 2018-07-25 07:38
Still same Problem with Skype V8.
Cheers

**Comment by dremin** [comment] 2018-08-01 23:46
I just downloaded the latest version of Skype and was unable to reproduce. Are you still having this issue with the latest version? Is there anything you need to do in order for the Skype window to stop responding to clicks?

**Comment by jacekmusial** [comment] 2018-08-03 19:55
I'm using latest Skype version on updated Win10 Pro and too, couldn't reproduce this issue.

**Comment by dremin** [comment] 2019-12-26 04:10
Unable to reproduce and the reported version of Skype is no longer supported; closing.

**Closed by dremin** 2019-12-26 04:10 UTC
