### ISSUE TITLE
[Feature Request] Show open Apps embedded in the Taskbar Icons

### ISSUE THREAD

**Issue by Light89** [cairoshell/cairoshell#546] opened 2021-03-25 07:39 UTC
I am mostly frustrated by the space the taskbar needs when I have several applications open. Nine to ten apps and the taskbar takes the whole screen.

![grafik](https://user-images.githubusercontent.com/27767482/112435082-901c5300-8d44-11eb-9457-8bd2445972e2.png)

It would be awesome, if the open apps would not show as an extra space taking tab-like icon but instead be embedded in the taskbar (fast startup) icons and, if there is no related icon in the fast startups, simply show a fitting icon the same size like the other icons. 
Mainly I'd love a behaviour like the current MacOs taskbar (showing open apps with a dot symbol).

**Comment by dremin** [comment] 2021-04-11 00:56
Thanks for the report! I believe this is a duplicate of #52, which is planned but not yet completed.

**Closed by dremin** 2021-04-11 00:56 UTC

**Comment by Light89** [comment] 2021-04-11 01:31
I see, thank you for the answer!
Might there be a way to contribute to this issue myself? I do not have much experience in working on a git project but I do study computer science and I do have some basic coding skills in java, c and python as well as some first git experience. I'd love to see this feature progress so if I might be of help, I'd love to!
Best regards,
Josephine

________________________________
Von: Sam Johnson ***@***.***>
Gesendet: Sonntag, 11. April 2021, 02:56
An: cairoshell/cairoshell
Cc: Light89; Author
Betreff: Re: [cairoshell/cairoshell] [Feature Request] Show open Apps embedded in the Taskbar Icons (#546)


Thanks for the report! I believe this is a duplicate of #52<https://github.com/cairoshell/cairoshell/issues/52>, which is planned but not yet completed.

**Comment by dremin** [comment] 2021-04-11 03:18
We welcome contributions! If you'd like to work on this, I am putting some of my notes in #52.

**Comment by Light89** [comment] 2021-04-11 05:51
That would be wonderful, yes please!
________________________________
