### ISSUE TITLE
Universal Windows Platform (UWP) application cannot be run (Messenger for Facebook)

### ISSUE THREAD

**Issue by tobiaspm** [cairoshell/cairoshell#482] opened 2020-11-12 10:42 UTC
Hi guys,
Could you please check this issue?

**Describe the bug**
Universal Windows Platform application cannot be run. When I tried to run the Messenger desktop application I got the following error message: Class not registered.

**Steps to reproduce**
1. Click to the Programs menu on the Menu Bar
2. Click to the Messenger application menu item
3. Get error message instead of running application

**Expected behavior**
Start application same as with original explorer.exe shell

**System information:**
 - Windows version: Windows 10, OS Build 19041.572
 - Cairo version: 0.3.7147.0
 - 32-bit or 64-bit: 64bit
 - In Cairo Settings > Advanced, is Cairo set as shell?: Yes

**Additional context**

**Screenshots**
![kép](https://user-images.githubusercontent.com/7899832/98929610-b18a4a00-24db-11eb-89bc-9a8021af8882.png)
![kép](https://user-images.githubusercontent.com/7899832/98929620-b5b66780-24db-11eb-8c50-e964abb083d1.png)

**Comment by dremin** [comment] 2020-11-21 07:54
This is unfortunately expected behavior when running alternate shells on Windows 10 without Explorer also running in the background. Running Cairo on top of Explorer (which is the default mode) is recommended to avoid this issue.

Closing as a duplicate of #365

**Closed by dremin** 2020-11-21 07:54 UTC

**Comment by tobiaspm** [comment] 2020-11-21 08:21
Hi @dremin ,
I see but I wanted to replace Explorer shell with Cairo because of performance and lagging issue with Explorer. Unfortunately, in this case Cairo shell won't be an alternative shell for me.
Thanks your answer.
