### ISSUE TITLE
Cairo screws up second monitor display

### ISSUE THREAD

**Issue by Eirinjas** [cairoshell/cairoshell#403] opened 2020-07-16 05:13 UTC
I use Dual Monitor Tools to swap applications between first and second monitor using shortcut keys.  This works fine with just Windows, but with Cairo running swapping a program from first monitor to second causes it to raise the display of the program a fair number of pixels up from the bottom of the screen so that the wallpaper is visible and the top of the it isn't ( cut off at the top because it exceeds bounds of monitor ).

**Steps to reproduce**
1.  Install current build of Cairo
2.  Install Dual Monitor Tools
3.  Run a fullscreen program
4.  Try swapping the program from one display to the other

**Expected behavior**
I expected the fullscreen app to switch from one display monitor to the other with no problem.  Windowed programs seem to be unaffected by this ( I don't mean borderless windowed mode ).

**System information:**
 - Windows version:  7 
 - Cairo version:  Version 0.3.7023.0 - Pre-release
 - 32-bit or 64-bit:  64
 - In Cairo Settings > Advanced, is Cairo set as shell?:   No

**Comment by Eirinjas** [comment] 2020-07-21 01:56
As an addendum:  If I "Set Cairo as Shell", the second monitor will not display at all.

**Comment by dremin** [comment] 2020-07-21 02:48
What application are you full screening? Could you provide some example apps that do this so that I can attempt to reproduce? Thanks!

**Comment by dremin** [comment] 2020-10-06 06:39
I installed Dual Monitor Tools and was able to identify an issue with menu bar/taskbar on multiple monitors not reacting to the full-screen window moving. I've made a fix for this issue, and you can test it early if you'd like by [installing this build](https://ci.appveyor.com/api/buildjobs/kcthk7tv0eu9lets/artifacts/Installer%2FCairoSetup_64bit.exe).

When Cairo is running as shell, and the key command used for Dual Monitor Tools includes the winkey, it ends up always moving the Cairo menu bar due to the programs menu activating on winkey down (this is a separate issue we should fix). If I use a different key command, there are no problems with this and Cairo running as shell either.

 I wasn't able to reproduce any of the other reported issues.

**Comment by dremin** [comment] 2020-10-10 01:30
The first issue referenced in my previous comment is resolved in the latest release.

**Closed by dremin** 2020-10-10 01:30 UTC
