### ISSUE TITLE
Notifications Area Icons Context menu

### ISSUE THREAD

**Issue by SuperMewio** [cairoshell/cairoshell#324] opened 2020-01-27 21:53 UTC
I use something from the Windows Store called EarTrumpet. It's a replacer for the default Volume Mixer that has a lot more features. The issue I am having is that Cairo makes the context menu for this program instantly disappear when I right click it, making the software almost useless when paired with Cairo. I am not sure what exactly is causing it.

You can reproduce this by installing EarTrumpet and right clicking it in the Notification Area Icons. The context menu will appear then disappear almost instantly

Now I am not sure if this is an issue with EarTrumpet or Cairo. EarTrumpet works fine when not using Cairo.

[EDIT] 

I am on Windows 10 version 1909

**Comment by josuave** [comment] 2020-01-27 22:06
Are you using cairo as the shell or are you using cairo on top of windows explorer.
What version of eartrumpet are you using

**Comment by josuave** [comment] 2020-01-27 22:32
Thank you

**Comment by SuperMewio** [comment] 2020-01-27 22:33
Of course, thank you for replying!

**Comment by dremin** [comment] 2020-01-28 22:43
This is because EarTrumpet responds to both WM_CONTEXTMENU and WM_RBUTTONUP messages, and we currently send both of those messages because when we receive a NotifyIconData struct in managed code, the version field is usually set to 0 instead of the version actually provided by the application.

We need to figure out why the version field is making it to managed code as 0, then we can intelligently send only the appropriate message to the window. WM_CONTEXTMENU should be sent instead of WM_RBUTTONDOWN/UP when version is at least 4, and should not be sent at all for lower versions.

Many shell-provided icons only respond to WM_CONTEXTMENU, so we need to keep sending both messages for the time being until we can properly support NotifyIconData versioning.

**Comment by SuperMewio** [comment] 2020-01-29 02:47
Ah, this makes sense. Thank you.

**Comment by dremin** [comment] 2020-01-29 08:51
Barring no regressions are found, this should be fixed in the next release (as well as the scrolling to adjust volume feature!) If you feel inclined, you can try [this build with the fixes](https://ci.appveyor.com/api/buildjobs/mt8no4e9jes5m655/artifacts/Installer%2FCairoSetup_64bit.exe).

**Comment by SuperMewio** [comment] 2020-01-29 17:13
Oh wow interesting. Testing that build does allow me to use the context menu for EarTrumpet in Cairo.

**Comment by dremin** [comment] 2020-02-07 16:25
This is fixed in the latest release.

**Closed by dremin** 2020-02-07 16:25 UTC
Labels: Bug
