### ISSUE TITLE
Cairo on multiple screens

### ISSUE THREAD

**Issue by tomtwentysix** [cairoshell/cairoshell#40] opened 2017-10-16 13:06 UTC
When running multiple screens, it would be good to have the option to have Cairo showing on all screens, similar to how you can have the windows taskbar on all screens. 

This is especially handy if you use a lot of fullscreen applications, as they cover cairo when open on the main screen.

**Comment by coldacid** [comment] 2017-12-20 20:32
Definitely would like to have this. +100.

**Comment by Krutonium** [comment] 2017-12-28 07:20
>This is especially handy if you use a lot of fullscreen applications, as they cover cairo when open on the main screen.

Would it be alright to make a feature request for having Cairo reserve space on the top of the screen and have the dock at the bottom disappear and reappear on mouseover when there is a fullscreen (non exclusive) window open? This would address the quoted part, and would also be really nice in a multimonitor environment as well.

**Comment by mdmk** [comment] 2017-12-31 14:50
@Krutonium Cairo already reserves space at the top of the screen, do you have a problem with windows overlapping the top bar?
As for the autohide, this is a duplicate of #48.

**Comment by dremin** [comment] 2018-01-02 22:49
If I understand correctly the main request here is to have the Cairo menu bar and taskbar duplicated across displays. This is something I am working towards but it might be a while before it is ready due to some prerequisite refactoring in how Cairo manages its windows.

**Comment by mdmk** [comment] 2018-01-02 23:17
I think that is it. In short, replicate basic bahaviour of Windows 10 with multiples taskbars. If possible, make separate option for enabling multiple menu bars and taskbars independantly.

**Comment by HeatedTea** [comment] 2018-01-31 15:41
When "Taskbar reserves space" is selected, space is reserved even on a second monitor where no Taskbar is displayed.

**Comment by dremin** [comment] 2018-01-31 16:25
@heatedtea I am not able to reproduce this on my triple monitor setup. Are you using Nvidia Surround or other similar software to merge displays?

**Comment by HeatedTea** [comment] 2018-01-31 16:33
@dremin No, but oddly I can't reproduce it either anymore.

**Comment by dremin** [comment] 2018-02-25 06:08
I have this working; if everything goes well it should make its way into the next build.

**Comment by dremin** [comment] 2018-03-02 02:32
This has been added in the latest release.

**Closed by dremin** 2018-03-02 02:32 UTC
Labels: Feature Request
