### ISSUE TITLE
Random Crash

### ISSUE THREAD

**Issue by TheXorog** [cairoshell/cairoshell#648] opened 2021-12-18 17:33 UTC
**Describe the bug**

I'm not quite sure how or why it happened but Cairo randomly crashed when launching Davinci Resolve 17. I can't seem to reproduce it, sadly. I thought i'll create an issue regardless.

**Steps to reproduce**

-/-

**System information:**
 - Windows version: Windows 10 21H1 (OS Build 19043.1415)
 - Cairo version: 0.4.164.51285
 - 32-bit or 64-bit: 64bit
 - In Cairo Settings > Advanced, is Cairo set as shell?: No

**Additional context**

I was running multiple things at the time: Task-Manager, a Minecraft server via the Git-Shell, a Minecraft-Client, Discord, Brave and MultiMC.

Log File
[12-18-2021-Backup.log](https://github.com/cairoshell/cairoshell/files/7739656/12-18-2021-Backup.log)

The message box that popped up, also attached as screenshot.
```
---------------------------
Cairo Desktop Error
---------------------------
Would you like to restart Cairo?



Please submit a bug report with a screenshot of this error. Thanks! 

Message: Illegal characters in path.

Target Site: Void RewrapException(System.Exception, System.Xaml.IXamlLineInfo, System.Uri)

Version: 0.4.164.51285



   at System.Windows.Markup.XamlReader.RewrapException(Exception e, IXamlLineInfo lineInfo, Uri baseUri)

   at System.Windows.FrameworkTemplate.LoadTemplateXaml(XamlReader templateReader, XamlObjectWriter currentWriter)

   at System.Windows.FrameworkTemplate.LoadTemplateXaml(XamlObjectWriter objectWriter)

   at System.Windows.FrameworkTemplate.LoadOptimizedTemplateContent(DependencyObject container, IComponentConnector componentConnector, IStyleConnector styleConnector, List`1 affectedChildren, UncommonField`1 templatedNonFeChildrenField)

   at System.Windows.FrameworkTemplate.LoadContent(DependencyObject container, List`1 affectedChildren)

   at System.Windows.StyleHelper.ApplyTemplateContent(UncommonField`1 dataField, De...
---------------------------
Yes   No   
---------------------------
```

**Screenshots**

![unknown (3)](https://user-images.githubusercontent.com/56395159/146650305-6f322685-8a67-4c2f-88fe-6fc2dc3d2dba.png)

**Comment by dremin** [comment] 2021-12-18 19:08
In Cairo Settings > Taskbar, is your "group windows by" setting set to "Application (Combined)"?

**Comment by TheXorog** [comment] 2021-12-19 02:46
Yes it is

![image](https://user-images.githubusercontent.com/56395159/146661844-114d7cc9-48e5-4ffa-9816-20f950ae9e19.png)

**Comment by dremin** [comment] 2021-12-19 06:28
Thank you for the details and the log! This is actually a duplicate of #645 so I will close this and continue to track the fix over on that issue.

**Closed by dremin** 2021-12-19 06:28 UTC
