### ISSUE TITLE
Cairo incorrectly handles the [Win] key

### ISSUE THREAD

**Issue by VulcanTourist** [cairoshell/cairoshell#193] opened 2018-08-25 19:59 UTC
**Describe the bug**
Cairo incorrectly grabs and "eats" the [Win] key on key-down rather than key-up and subjects the key to keyboard repeat, wrecking an entire ecosystem of hotkeys and custom keybinds.  It can no longer be used as the modifier key that was intended.  Now, holding the key down as a modifier instead causes the Cairo menu to repeatedly open and close.

**Steps to reproduce**
1. Press and hold the [Win] key, intending to press any other key in combination with it.

**Expected behavior**
It should behave as a modifier key.

**System information:**
 - Windows version: Windows 10 x64
 - Cairo version: 0.3.6701.0 (set as shell)

**Comment by dremin** [comment] 2018-08-27 23:59
Can you confirm that this only happens while Cairo is set as shell?

**Comment by VulcanTourist** [comment] 2018-08-28 03:17
I can't, since I'm no longer using it as explained in [my other comment](https://github.com/cairoshell/cairoshell/issues/194#issuecomment-416400847).

**Comment by josuave** [comment] 2018-09-16 15:00
I have submitted a push that should solve this.

**Comment by Obbi89** [comment] 2019-06-19 19:44
I can confirm that if Cairo is the shell none of the [Win] shortcuts work.
I guess explorer might be handling those. This means that it might be a good idea to implement some of them directly in cairo and hook them up if cairo is set as shell.
Stuff like:

Win+R -> Run
Win+E -> Open file explorer
Win+U -> Open accessibility settings
Win+Arrow Up/Down Max/Minimize Window
etc.

Maybe even allow custom hotkeys?

**Comment by josuave** [comment] 2019-06-20 01:05
The original request was specifically the win key. I recommend splitting your request out as a new feature request for a Cairo Hotkey Manager. Use the issue template for feature requests, the more specific you are the better the community can contribute as a whole

**Comment by dremin** [comment] 2020-08-21 03:12
Closing since this has been resolved.

**Closed by dremin** 2020-08-21 03:12 UTC
