### ISSUE TITLE
Cairo won't hide the Windows Taskbar

### ISSUE THREAD

**Issue by dragonfirecmv** [cairoshell/cairoshell#56] opened 2017-11-11 09:49 UTC
After looking through the source code, I've noticed that the SWP_HIDEWINDOW is set to 128 instead of 80 and the SWP_SHOWWINDOW is set to 64 instead of 40 (you've commented it out). Why? The ones that you've commented out are the correct ones.

**Comment by dremin** [comment] 2017-11-11 22:52
That's really old code--not sure why, but I'll look into it! The current code hides the taskbar on my systems, which OS are you running where it isn't working?

**Comment by dragonfirecmv** [comment] 2017-11-11 23:35
Windows 10 FCU. Also, every tutorials mention it being 80 and 40 instead of 128 and 64 -- I also noticed that there's some kind of race between AutoHide and SWP_HIDE (you need to use AutoHide first if you wanted to claim the space the Taskbar was using). My take on the fix is that calling the AutoHide from the Window Constructor, then using the SWP_HIDE on the Window_Loaded event.

**Comment by dragonfirecmv** [comment] 2017-11-12 03:40
Oops, discovered a bug. It seems that some triggers (not the windows button) can actually unhide the taskbar. I've also discovered a program called Taskbar Magic, unfortunately I don't really know how it circumvent this.

**Comment by dragonfirecmv** [comment] 2017-11-13 09:40
My workaround for this issue: Use a BackgroundWorker to anually repeat the calls of SetWindowsPos.

**Comment by dremin** [comment] 2017-11-17 00:01
@dragonfirecmv In what scenarios are you seeing the taskbar re-appear? I haven't seen this at all; I'm wondering if you are doing something that I haven't tried or if you have another application running in the background that is causing this to happen.

**Comment by dremin** [comment] 2017-11-17 02:02
Regarding the SWP values, this is simply an int/hex conversion. 0x40 = 64 and 0x80 = 128.

**Comment by dragonfirecmv** [comment] 2017-11-17 03:30
Usually the taskbar reappears occasionally when: Hitting the start button, Opening Flyouts like the View Available Network, Opening programs and Programs that needs attention(taskbar app icon blinking). That's about it so far.

**Comment by dremin** [comment] 2017-11-17 06:03
Interesting, I can't reproduce this behavior. However, I have refactored how the Windows taskbar is hidden for Milestone 3 so hopefully you will see better results in M3 builds.

**Comment by dremin** [comment] 2017-11-28 05:39
This is fixed in the latest Milestone 3 release. Please check for updates and re-open the issue if it is not resolved.

**Closed by dremin** 2017-11-28 05:39 UTC
