### ISSUE TITLE
Inconsistent gaps between buttons on taskbar

### ISSUE THREAD

**Issue by Matthew-Bonner** [cairoshell/cairoshell#281] opened 2019-11-01 11:22 UTC
When the taskbar is full width, there are gaps between some of the buttons, this looks a wee bit strange so I was wondering if this was something you would consider changing?

![image](https://user-images.githubusercontent.com/7858744/68021603-ceb9f500-fc99-11e9-8ff6-23649382b8d8.png)

**Comment by dremin** [comment] 2019-11-10 03:36
This is actually intentional. The taskbar groups buttons by category of app, as specified in the App Grabber. I suppose this could become optional as a setting if desired.

**Comment by Matthew-Bonner** [comment] 2019-11-12 13:13
I think the grouping is therefore unclear, what is the correlation between the groups in the screenshot I provided?

**Comment by dremin** [comment] 2019-11-13 00:02
The correlation is using categories defined during the initial setup, or during subsequent App Grabber runs. Essentially, it should match the Programs menu in terms of how the taskbar icons are grouped. The taskbar list button on the far right should display this as well.

**Comment by dremin** [comment] 2019-12-26 03:57
Working as intended; closing.

**Closed by dremin** 2019-12-26 03:57 UTC
