### ISSUE TITLE
No battery or wifi icons on ASUS TUF FX505DY

### ISSUE THREAD

**Issue by Sansyyxd** [cairoshell/cairoshell#310] opened 2020-01-25 13:41 UTC
I rebooted my laptop and there are missing icons on the taskbar (Battery Icon and Wifi Icon)

**Steps to reproduce**
1.  Reboot an ASUS laptop
2. They're not there
3. Try with shell replaced

**Expected behaviour**
it wont show

**System information:**
 - Windows version: Windows 10
 - Cairo version: Latest Build (0.3.6842.0)
 - 32-bit or 64-bit: 64-Bit
 - In Cairo Settings > Advanced, is Cairo set as shell?: yes

**Additional context**

**Screenshots**

**Comment by josuave** [comment] 2020-01-25 17:01
Duplicate of #146

**Comment by Sansyyxd** [comment] 2020-01-25 17:20
its by windows confirmed by running the explorer shell and rerunning cairo and it shows up

**Comment by dremin** [comment] 2020-01-25 18:46
These icons are currently populated by Explorer. If Cairo is set to run at startup instead of as shell, these icons should work. Implementing these icons for while Cairo is running as shell is covered by #146.

**Comment by dremin** [comment] 2020-03-16 07:28
This is implemented in [this build](https://ci.appveyor.com/api/buildjobs/cx8chb4t09mgeflw/artifacts/Installer%2FCairoSetup_64bit.exe) if you would like to give it a try before release.

**Comment by dremin** [comment] 2020-03-23 02:57
These icons should now be present in the latest release.

**Closed by dremin** 2020-03-23 02:57 UTC
