### ISSUE TITLE
Error: Object reference not set to an instance, Version 0.4.164.51285

### ISSUE THREAD

**Issue by Beatzka** [cairoshell/cairoshell#644] opened 2021-12-08 08:13 UTC
I'm very happy with your Cairo Desktop Evironment. Thanks a lot for your great work!

**Bug Description**
But this morning I updated my Cairo Desktop installation to Version 0.4.164.51285.
Re-starting Cairo Desktop after installation lead to the following error:

Message: Object reference not set to an instance of object.
Target Site: CairoDesktop.AppGrabber.CategoryList.Deserialize(String ConfigFile)
[...]

Please see the attached screenshot for the details.

![CairoDesktopError](https://user-images.githubusercontent.com/95741210/145172415-f930796d-a7ed-43d1-9e0e-69575210af79.png)

If I acknowledge the error dialog with "Yes" the same message just appears again.
If I acknowledge it with "no" the dialog disappears but nothing else happens and the process "CairoDesktop.exe" still keeps running in the background.

So I switched back to Version 0.4.158.53003 of Cairo which still works fine for me.

**System information**
OS: Microsoft Windows 10 Enterprise 21H2 Build 19044.1348
.NET Full: 4.8.04084

**Comment by Mach28** [comment] 2021-12-11 22:35
Same thing here. Windows 11, Version 10.0.22000, Build 22000

**Comment by dremin** [comment] 2021-12-11 22:41
Could you please upload your `%appdata%\CairoAppConfig.xml` file so I can try to reproduce? Thanks!

**Comment by Williwillswisse** [comment] 2021-12-12 06:43
Hi, same problem here.
This ist the file renamed to .txt because Github doesn't support .xml
[CairoAppConfig.txt](https://github.com/cairoshell/cairoshell/files/7698228/CairoAppConfig.txt)

**Comment by dremin** [comment] 2021-12-12 07:17
@Williwillswisse Thanks, this was helpful. I believe I have fixed the issue, could you please put your old xml file back in and test [using this Cairo build?](https://github.com/cairoshell/cairoshell/suites/4629467639/artifacts/125358111) (GitHub login required)

**Comment by Williwillswisse** [comment] 2021-12-12 07:36
I've done the following steps:
Install Cairo via update -> crash
kill Cairo via task manager
install Cairo via your new x64 setup
--> it works 😀

Thanks for this great tool.

**Comment by dremin** [comment] 2021-12-24 06:42
The fix is in the latest release.

**Closed by dremin** 2021-12-24 06:42 UTC
