### ISSUE TITLE
Network applet open from bottom of the screen instead from top

### ISSUE THREAD

**Issue by KhazAkar** [cairoshell/cairoshell#366] opened 2020-04-03 08:03 UTC
**Describe the bug**
Network applet open from bottom of the screen instead from top

**Steps to reproduce**
1. Have Windows taskbar on bottom
2.  Launch CairoShell
3. Access network applet

**Expected behavior**
it should open from top of the screen

**System information:**
 - Windows version: Windows 10 1803
 - Cairo version: Version 0.3.6984.0 - Pre-release
 - 32-bit or 64-bit: 64 bit
 - In Cairo Settings > Advanced, is Cairo set as shell?: No

**Additional context**
Workaround: Set windows taskbar to appear on top before launching CairoShell, then it works

**Comment by josuave** [comment] 2020-04-03 16:46
I encountered this also. Mu solution was to move the taskbar prior to running Cairo on top of Windows. I have looked into moving the taskbar via code with no success.

**Comment by dremin** [comment] 2020-04-03 16:57
We need to handle the ABM_GETTASKBARPOS message by returning a rect of the menubar clicked. I attempted this once but had some challenges with marshalling between the C++ and managed code, but it's worth investigating some more.

**Comment by dremin** [comment] 2020-04-04 05:45
@KhazAkar I've made some changes that should resolve the issue in [this build](https://ci.appveyor.com/api/buildjobs/me9npmvckmkxyt5s/artifacts/Installer%2FCairoSetup_64bit.exe) if you would like to try. Thanks!

**Comment by KhazAkar** [comment] 2020-04-06 09:59
And on your build it stopped hiding windows task bar on second screen

**Comment by dremin** [comment] 2020-04-06 14:23
@KhazAkar Does that issue persist after logging out and back in?

**Comment by KhazAkar** [comment] 2020-04-07 07:22
No, but still you need to lock machine and unlock it to fix that problem

**Comment by dremin** [comment] 2020-04-07 11:02
Does the problem go away when going back to 0.3.6984?

**Comment by KhazAkar** [comment] 2020-04-08 06:15
I need day or two to check it because it happened randomly, mostly when sharing second screen or just working on second screen. On that build from you it can happen several times a day

**Comment by KhazAkar** [comment] 2020-04-08 08:54
Well, It showed when trying RDP connection and now I can uncover windows task bar on second screen.

**Comment by dremin** [comment] 2020-04-08 15:36
Thanks for the details. I have some ideas on how this can be improved and will let you know when I have something for you to try. I am not able to reproduce the issue on my machines, but they are on 1903 and 1909, I don't have any on 1803 still.

**Comment by dremin** [comment] 2020-04-09 03:53
@KhazAkar Could you please try [this build](https://ci.appveyor.com/api/buildjobs/vsawtwtnsgcm0b8m/artifacts/Installer%2FCairoSetup_64bit.exe)?

**Comment by dremin** [comment] 2020-04-15 14:49
The issue as opened has been resolved in the latest release. Please open a separate issue if the taskbar showing continues to be an issue.

**Closed by dremin** 2020-04-15 14:49 UTC
Labels: Bug
