### ISSUE TITLE
Explorer windows flicker when clicking cairo menu bar and then the desktop

### ISSUE THREAD

**Issue by beppe9000** [cairoshell/cairoshell#263] opened 2019-05-26 16:07 UTC
Not set as shell, taskbar disabled

**Comment by dremin** [comment] 2019-07-02 03:28
Not able to reproduce, any shell extensions you have installed that could be causing this?

**Comment by beppe9000** [comment] 2019-07-02 12:04
I have lots of shell extensions... here is a dump:
![image](https://user-images.githubusercontent.com/6625123/60511446-44a15600-9cd2-11e9-9963-bb72e8278599.png)

**Comment by dremin** [comment] 2020-02-15 02:50
I think this is resolved in the latest release after the desktop changes. Could you please verify? Thanks!

**Comment by beppe9000** [comment] 2020-02-15 22:15
it looks solved. but I got a flicker of the desktop on some occasions on current version by doing random clicks on desktop, top bar and then minimize/restore of a window. looks like a desktop refresh idk if it's related

**Comment by dremin** [comment] 2020-02-15 22:36
Interesting, would you be able to provide a screen recording showing the flicker? I am not able to reproduce that one.

**Comment by beppe9000** [comment] 2020-02-17 13:59
I originally intended to, but the gif recording had a too slow frame rate :\ 
I will figure something...

**Comment by dremin** [comment] 2020-08-21 03:51
Closing due to no further reproductions.

**Closed by dremin** 2020-08-21 03:51 UTC
