### ISSUE TITLE
Cairo as Shell breaks Wifi Pop-Up

### ISSUE THREAD

**Issue by Dinoraptor101** [cairoshell/cairoshell#501] opened 2020-12-14 15:06 UTC
**Describe the bug**

**Steps to reproduce**
1. Switch to Cairo as Shell
2. Restart Computer
3. Click the Wifi icon to change network

**Expected behaviour**
The Wifi selection pop-up should appear but instead, it does not load, there is no alternative method to switching or joining wifi networks while using Cairo as Shell.

**System information:**
 - Windows version: 
 - Cairo version: 
 - 32-bit or 64-bit: 
 - In Cairo Settings > Advanced, is Cairo set as shell?: 

**Additional context**

**Screenshots**

**Comment by dremin** [comment] 2020-12-14 22:17
Thanks! This is a duplicate of #365

**Closed by dremin** 2020-12-14 22:17 UTC

**Comment by ivellios1988** [comment] 2022-10-20 11:50
Same issue here. Windows 10 21H2 x64
