### ISSUE TITLE
Full Width Taskbar DesktopOverlay and Tasklist Press Style Incorrect

### ISSUE THREAD

**Issue by josuave** [cairoshell/cairoshell#367] opened 2020-04-04 02:12 UTC
**Describe the bug**
When click either DesktopOverlay or Tasklist when the taskbar is set to full width still shows a curved corner

**Steps to reproduce**
1. Click it and observer

**Expected behavior**
Style for pressed button should not have a curved corner

**Comment by dremin** [comment] 2020-04-08 01:28
Is this a duplicate of #295?

**Comment by josuave** [comment] 2020-04-08 01:45
Hmmm, i will have to try the different styles. I think i was using default style rather than flat.

**Comment by josuave** [comment] 2020-06-12 12:08
This is a duplicate of #295. I am closing

**Closed** 2020-06-12 12:08 UTC
