### ISSUE TITLE
[Feature Request] Task List shortcut

### ISSUE THREAD

**Issue by Gentle888** [cairoshell/cairoshell#134] opened 2018-04-16 18:23 UTC
Win+Tab maybe?

**Comment by dremin** [comment] 2020-08-21 01:57
Closing- this would still require mouse movement to the same section of the display, which removes the utility of the shortcut. Even if it cycled through apps, that is a duplicate of existing alt-tab functionality.

**Closed by dremin** 2020-08-21 01:57 UTC
