### ISSUE TITLE
[BUG][Settings] "Restart Cairo to apply" button only terminates Cairo

### ISSUE THREAD

**Issue by coldacid** [cairoshell/cairoshell#214] opened 2018-11-02 14:47 UTC
**Describe the bug**
Clicking the "Restart Cairo to apply" button in Cairo Settings closes Cairo shell, but does not restart it.

**Steps to reproduce**
1. Change an option in Cairo Settings.
2. Click the "Restart Cairo to apply" button under the page tabs in the Cairo Settings window.

**Expected behavior**
The current Cairo shell process should terminate, and a new one started.

**System information:**
 - Windows version: Windows 10 version 1803 (OS Build 17134.345)
 - Cairo version: 0.3.6746.0
 - 32-bit or 64-bit: 64-bit
 - In Cairo Settings > Advanced, is Cairo set as shell?: No

**Additional context**

**Screenshots**

**Comment by dremin** [comment] 2018-12-01 19:00
I'm unable to reproduce this. Is it still happening?

**Comment by coldacid** [comment] 2018-12-05 14:55
Looks to be working now, but it takes a lot longer than just starting it up directly.

**Comment by dremin** [comment] 2020-01-21 00:36
Closing due to lack or reproduction.

**Closed by dremin** 2020-01-21 00:36 UTC
