### ISSUE TITLE
Universal Windows Platform Support Cairo as Shell Mode

### ISSUE THREAD

**Issue by mealpi** [cairoshell/cairoshell#374] opened 2020-04-15 14:16 UTC
Please add support Universal Windows Platform (UWP) for Cairo as Shell Mode.
UWP Apps not working on Cairo Shell Mode.

**Comment by AnErrupTion** [comment] 2020-04-23 07:14
The dev could add an option to use the shell to execute programs. (ProcessStartInfo.UseShellExecute set to false for UWP programs for example)

**Comment by artdeell** [comment] 2020-05-15 20:01
Yeah. Someone should contribute UWP support, because, hey, i can't view images with Windows-integrated tool.

**Comment by josuave** [comment] 2020-06-12 12:04
@dremin we should create a low level [feature request] and close these requests in favor of it.

**Comment by dremin** [comment] 2020-06-14 02:15
@josuave I agree, or edit an existing issue to make it more appropriate as a catch-all for duplicates.

**Comment by dremin** [comment] 2020-10-24 21:26
Closing as duplicate of #365

**Closed by dremin** 2020-10-24 21:26 UTC
