### ISSUE TITLE
Add the ability to combine icons for the same programs, like on the normal Windows Taskbar

### ISSUE THREAD

**Issue by MysteriousFigure** [cairoshell/cairoshell#548] opened 2021-04-08 12:25 UTC
I have had a look, and there is no way currently to group together the same programs on the taskbar, and so if I have multiple windows open for the same program, the taskbar gets really messy, which is inconvenient

Is there a way that the same programs could be combined together under one tab? (like in windows where if you hover over the icon in the tab it shows you all the instances)

My current issue with the taskbar in Cairo:
![Example of the issue in Cairo](https://user-images.githubusercontent.com/53799162/114025941-998ddb00-986d-11eb-89df-71245a28f014.jpg)
The aforementioned Windows taskbar with combined icons:
![Windows Example of combined icons](https://user-images.githubusercontent.com/53799162/114025942-9a267180-986d-11eb-8221-73a0e2e170ce.jpg)

**Comment by dremin** [comment] 2021-04-11 00:56
Thanks for the report! I believe this is a duplicate of #52, which is planned but not yet completed.

**Closed by dremin** 2021-04-11 00:56 UTC
