### ISSUE TITLE
option to change position of MenuBar to the bottom

### ISSUE THREAD

**Issue by ivan8994** [cairoshell/cairoshell#801] opened 2024-04-24 17:12 UTC
_this suggestion is based on the fact that TaskBar can be repositioned_

currently it is **possible** to place **_TaskBar_** at the Bottom of the screen, or at the Top of the screen 

would be great to have the same option for **_MenuBar_**

for example, user clicked on **_curently avaliable_** option of TaskBar and placed it **at the top of the screen**. in this case,  user have both TaskBar and MenuBar **at the top**. What if user wants to place TaskBar at the top (currently **_possible_**) and place MenuBar to the bottom (currently **_not possible_**)  , to perform a switch. would be great to have **_MenuBar_** as flexible as TaskBar **_already_** is, in similar way

**current**
![current cairo 01](https://github.com/cairoshell/cairoshell/assets/75372078/82a79f1b-9173-49b5-8fad-6cb78b797637)

**concept**
![feature cairo 01](https://github.com/cairoshell/cairoshell/assets/75372078/1bcdc085-5dfe-4531-9849-449207a2575d)

I believe this approach might significantly impact the productivity of end-user in terms of multitasking workflow in positive manner , because a regular user is used to operate with switching between elements in the top area of the screen (tabs of web browser foe example) , so it might meet the organic feel of " windows switching" process 

also, ther are several proprietary apps (like Stardock Goupy) that works in a similar way (in terms of global concept) so potentionally Cairoshell may have more new users if having this feature 

thus it will also be possibel to add Cairoshell into more categories of the apps on Alternative.To , thus expanding the recognition of the CairoShell

**Comment by dremin** [comment] 2024-05-24 07:20
I am working on adding this option. It is a duplicate of #142.

**Closed by dremin** 2024-05-24 07:20 UTC
