### ISSUE TITLE
Windows Taskbar disappears when apps go fullscreen with Cairo running

### ISSUE THREAD

**Issue by JacobSC51** [cairoshell/cairoshell#377] opened 2020-04-16 10:00 UTC
If Cairo is opened, and it's own taskbar is disabled, the Windows system taskbar disappears when going into fullscreen mode in apps and then exiting out of it. This does not happen if Cairo is not running, the only thing that fixes it is restarting explorer.exe

 - Windows version: Windows 10 Pro 1909
 - Cairo version: 0.3.7015.0 - Pre-release
 - 64-bit
 - explorer.exe shell

![image](https://user-images.githubusercontent.com/47087244/79442779-46c27000-7fd9-11ea-91fe-48f5c3457161.png)
![image](https://user-images.githubusercontent.com/47087244/79442810-50e46e80-7fd9-11ea-92ab-8e01c8eaab7a.png)

**Comment by dremin** [comment] 2020-04-17 22:50
@JacobSC51 Sorry about the regression! Could you please try [this build](https://ci.appveyor.com/api/buildjobs/nsp594s9juxgxb8f/artifacts/Installer%2FCairoSetup_64bit.exe) and report back if the issue is resolved for you?

**Comment by JacobSC51** [comment] 2020-04-18 08:27
I've installed it and it seems to have fixed the taskbar problem.

**Comment by dremin** [comment] 2020-04-18 20:54
Great! The fix will be included in the next release, but feel free to keep using this version until then!

**Comment by LoTechFo** [comment] 2020-07-13 09:36
I can't even find a way to use the windows taskbar while Cairo is running at all. Amy hints?

(I know this isn't the right place for advice or tips, but this is literally the only page on the entire internet discussing this issue)

**Comment by josuave** [comment] 2020-07-13 12:00
1. Open "Cairo Settings"
2. Go to the "Taskbar" tab
3. Uncheck the box for "Enable Taskbar"

**Comment by LoTechFo** [comment] 2020-07-14 07:39
I tried that, for me it just disabled the Cairo taskbar but did not enable windows taskbar.

I ended up going into the windows settings and checking "autohide" then unchecking it, the issue persisted, then I  restarted my PC and all is working

**Closed** 2020-07-21 01:20 UTC
Labels: Bug
