### ISSUE TITLE
Restoring minimized windows from Cairo taskbar is a bit broken

### ISSUE THREAD

**Issue by JacobSC51** [cairoshell/cairoshell#564] opened 2021-05-07 10:04 UTC
When clicking on a minimized program on the Cairo taskbar, some windows appear resized to a small resolution (like Microsoft Teams), some don't get resized but only a part of them renders until I hover on the title bar while the rest is just white (like Firefox). Not only that, the window restore animations always play starting from the position of the Windows taskbar even when using the Cairo one. And the window restore/minimize sounds never play when clicking on programs on the Cairo taskbar.

**System information:**
 - Windows version: Windows **10** Pro **64-bit** 20H2 19042.928
 - Cairo version: **0.4.80.38114**
 - is Cairo set as shell?: **No**

**Screenshot**
![obraz](https://user-images.githubusercontent.com/47087244/117433019-86c4ff80-af1a-11eb-8386-55fbd5af2d40.png)

**Comment by dremin** [comment] 2021-05-07 16:49
Interesting, I thought this was just a Firefox issue but it does seem like this could be caused by us. Thanks for the report, I'll look into it!

**Comment by dremin** [comment] 2021-05-20 16:39
I think the Firefox issue only occurs when WebRender is enabled in Firefox, so it's possible this isn't actually us. I will need to investigate more with Spy++ to see if there are different messages sent to windows by Explorer.

**Comment by dremin** [comment] 2021-11-26 22:50
Forgot to close this earlier; it's fixed in the latest release.

**Closed by dremin** 2021-11-26 22:50 UTC
Labels: Bug
