### ISSUE TITLE
Option to not creat additional task button when launching from Quick Launch

### ISSUE THREAD

**Issue by Gentle888** [cairoshell/cairoshell#99] opened 2018-03-11 16:25 UTC
Please, make taskbar work like the Mac one. If launching from quick launch liks makes another button in taskbar, it just doesn't make any sense.

Also, there must be an option to choose how multiple stacked tasks will work:

1) Pressing switches task between one another
2) Pressing opens pop-up with opened tasks, here's explanative picture

![cairo feauture](https://user-images.githubusercontent.com/32046895/37255751-ab7749da-2572-11e8-812d-e1c58817eee4.png)

**Comment by mdmk** [comment] 2018-03-11 18:04
This is more or less a duplicate of #52.
I don't get the point of option 1.
If you mind developing on the matter.
As option 2, thumbnail should be proposed as well (but optional to limit impact on resources).

**Comment by Gentle888** [comment] 2018-03-13 19:44
> As option 2, thumbnail should be proposed as well (but optional to limit impact on resources).

I think this should be an option too.

**Comment by dremin** [comment] 2020-08-21 00:55
Duplicate of #52, closing

**Closed by dremin** 2020-08-21 00:55 UTC
