### ISSUE TITLE
flickering and bottom margin when connecting to a session over RDP

### ISSUE THREAD

**Issue by kunago** [cairoshell/cairoshell#578] opened 2021-05-26 07:26 UTC
**Describe the bug**
The title pretty much describes it. It started happening at version 0.4.80, or maybe the previous one but since the timeframe between releases was too short, I might not have noticed. When I connect to an open session over RDP, which I use daily, the Cairo taskbar placed on top of my screen starts flickering and eventually adds a margin..

I will use CSS to describe the problem. It's placed with "position: absolute, top: 0" under normal circumstances. When I connect to a running session, it starts to jump back and forth and alternating between "top: 0" and "top: 100px" (example). There already is a margin on top created for the jumping. It keeps on happening for a few seconds rapidly changing its position until it settles on top again but laving the margin-bottom: 100px.

This is a screenshot when it settles down:
![image](https://user-images.githubusercontent.com/460971/119618763-8c1fb680-be03-11eb-95e1-47b734a81080.png)

The flickering happens like this:
![image](https://user-images.githubusercontent.com/460971/119619156-f9334c00-be03-11eb-8355-f955b01892d6.png)

**Steps to reproduce**
1. start a session, it does not matter whether over RDP or normally
2. disconnect
3. reconnect over RDP

**Expected behavior**
No margin and no flickering, no jumping on connection to a running session.

**System information:**
 - Windows version: Windows 10 Home, version 20H2, build 19042.985
 - Cairo version: 0.4.112.21595
 - 32-bit or 64-bit: 64-bit
 - In Cairo Settings > Advanced, is Cairo set as shell?: no

**Additional context**
It might also be a bug in the taskbar position, being placed on top rather than at the bottom.
EDIT: this is by default, I did not realize at first.

**Screenshots**
See above.

**Comment by dremin** [comment] 2021-06-03 21:44
By chance are the resolution or scaling settings different when connecting via RDP?

**Comment by lss4** [comment] 2021-07-28 05:58
I've the same issue on 0.4.133.47321 with Windows 10.

Same issue as OP when accessing a system running Cairo Shell via RDP. Screen flickers, and that all icons and windows are restricted to only the middle part of the screen, with a big margin to the top and bottom.

In my case the RDP is being launched full-screen and I don't have any different resolution/scaling settings between host and target.

**Comment by dremin** [comment] 2021-07-30 21:57
Would you be able to provide a screen recording showing the issue?

**Comment by lss4** [comment] 2021-07-31 03:56
[out.ogv.zip](https://github.com/cairoshell/cairoshell/files/6910634/out.ogv.zip)
I'm able to barely record a little bit of the phenomenon.

I'm accessing the remote desktop via Remmina from a Linux host but in reality how you connect to the remote desktop doesn't really matter.

Note the placement of icons. Windows are also only allowed to display in the middle part of the screen. Top and bottom areas of the screen are not accessible.

On the other hand, if you can make a Win10 VM it would be very trivial to reproduce.
1. Create a Win10 VM.
2. Install Cairoshell on it.
3. RDP to that VM.
And you'll see the issue.

**Comment by dremin** [comment] 2021-08-04 17:07
@lss4 Thanks! This is very interesting. What virtualization platform are you using?

**Comment by lss4** [comment] 2021-08-04 22:11
I mostly use Oracle VirtualBox but I think the problem is not really related to the whether the target is real or virtual (the one I RDP'd to was a real one). A VM would be an easy way to test RDP.

Also, I noticed that if I close Cairo and restart it, initially there would not be any issue, but if I RDP to the same system again the issue will reappear with a small margin. The margin seems to increase every time I RDP into the system until it reaches a maximum.

I did not recall seeing the issue before as I started using Cairo on that system since around version 0.3.x. Only recently.

**Comment by dremin** [comment] 2021-08-05 01:32
Thank you for the detail, I really appreciate it. I'm now able to reproduce the issue! While I work on a fix, could you please try enabling these Cairo settings as a workaround?

- Menu Bar > Show menu bar on multiple monitors
- Taskbar > Show taskbar on multiple monitors

Even if multiple monitors aren't in use, this setting seems to avoid the bug in my testing.

**Comment by lss4** [comment] 2021-08-05 02:12
Should also point out that logging back in to the machine physically after having RDP'd to the system before would also trigger the flickering and increase the top/bottom margin.

The two settings you mentioned worked around this issue. When I log back in to the system via RDP again after setting them, everything returned to normal.

**Comment by dremin** [comment] 2021-08-05 03:16
@lss4 Could you please test [this build](https://github.com/cairoshell/cairoshell/suites/3416474356/artifacts/80810571) using your normal settings (the two options above disabled) and let me know if it is working properly now? You should also see less flickering.

**Comment by lss4** [comment] 2021-08-05 03:33
Just did a few tests after installing this build, with the workarounds disabled.

It seems the issue has gone away. I don't get the flicker or margin anymore when I log in to the system, either via RDP or directly. So this build works for me.

Don't know if OP or others can test if the build works for them as well.

**Comment by dremin** [comment] 2021-11-28 19:20
This is resolved in the latest release.

**Closed by dremin** 2021-11-28 19:20 UTC
