### ISSUE TITLE
Keyboard media keys aren't working

### ISSUE THREAD

**Issue by HaLPaX** [cairoshell/cairoshell#477] opened 2020-10-30 14:19 UTC
I can't increase and decrease volume and other functions using media control keys present on my keyboard, it works only if Windows' default shell is running in background.

**Comment by Blackrucat** [comment] 2020-10-30 19:04
A lot of people already did the same Feature Request, but they don't listen to us.

**Comment by dremin** [comment] 2020-10-31 02:47
Thanks for the report! This is a duplicate of #409 which is where we will track the progress of this item.

**Closed by dremin** 2020-10-31 02:47 UTC
