### ISSUE TITLE
Crash of EarTrumpet

### ISSUE THREAD

**Issue by mdmk** [cairoshell/cairoshell#77] opened 2018-01-08 17:19 UTC
I tried [EarTrumpet](https://github.com/File-New-Project/EarTrumpet/releases) (latest binary builds ont the Microsoft Store, those on github are outdated) to replace the sound tray icon that currently doesn't work (#50).
I encounter a crash when lauched after Cairo, of after a few click if lauched before Cairo.
[here](https://gist.github.com/mdmk/bc697000ccf3f34f8ed694b65733cb07) the detail of the error.
Tell me if you need more information.

**Comment by dremin** [comment] 2018-01-16 01:07
Try disabling "Periodically re-establish notification area hook" in Cairo Settings > Menu Bar.

This is ultimately a bug in EarTrumpet making assumptions about the taskbar window, but this should work around that.

**Comment by riverar** [comment] 2018-01-17 04:09
This is a Cairo appcompat bug, marking it as an enhancement

**Comment by riverar** [comment] 2018-01-17 04:10
Cairo needs to handle this for appcompat, not a bug on third-party apps.

**Comment by dremin** [comment] 2018-01-17 04:22
[I created an issue for this in the EarTrumpet repo.](https://github.com/File-New-Project/EarTrumpet/issues/181)

**Comment by mdmk** [comment] 2018-01-17 17:54
It does work with "Periodically re-establish notification area hook" thanks.
I notice network tray is almost functional with this disabled.
If you let the option ticked and spam sound tray icon, then network will not function anymore.
But if unticked network is not affected and works almost correctly (often need to click two times for the popup to appear)

**Comment by dremin** [comment] 2018-05-12 22:10
This is resolved with the latest version of Cairo and EarTrumpet 1.5.3.0 or later.

**Closed by dremin** 2018-05-12 22:10 UTC
