### ISSUE TITLE
Top panel hids itself randomly

### ISSUE THREAD

**Issue by Gentle888** [cairoshell/cairoshell#104] opened 2018-03-14 10:33 UTC
Cant reproduce. It's totally random.

**Comment by dremin** [comment] 2018-03-18 04:19
Have you been able to find reproduction steps? For example, seeing if it happens without other apps running, happening only with Cairo or Explorer as shell, etc. Otherwise, I will have to close this since I am unable to reproduce this (haven't seen it happen to be honest)

**Comment by dremin** [comment] 2018-04-22 21:33
Closing due to lack of reproduction steps. Please re-open if you are able to figure out what steps causes this to happen on your machine.

**Closed by dremin** 2018-04-22 21:33 UTC
