### ISSUE TITLE
Working built in Virtual Desktops

### ISSUE THREAD

**Issue by 69pewpiepie** [cairoshell/cairoshell#599] opened 2021-06-24 03:00 UTC
Cairo Shell does not currently have a virtual desktops feature.

_But you can run Cairo Shell on top of Windows Explorer shell for Task View!!!_

Cairo **still** shows you all your windows from all your desktops (I tried it on Windows 10 20H2 btw)

Cairo Shell should hide all windows that are not in the desktop I am in, as it should be.

Or...

Cairo Shell should add its own working virtual desktops feature if I want to set Cairo as my default shell. Similar to GNOME's workspaces "Activities" feature.

Other old shells, such as bbLean which actually works on Windows 10 despite it being not updated since 2008, have managed to master this with no problem. (You can try it by going here: http://bb4win.sourceforge.net/bblean and set it as the default shell by running bsetshell.exe and try the workspaces)

**Comment by dremin** [comment] 2024-12-02 01:38
Closing as duplicate of #398, which I have a fix coming for.

**Closed by dremin** 2024-12-02 01:38 UTC
