### ISSUE TITLE
Installing

### ISSUE THREAD

**Issue by BigT2013** [cairoshell/cairoshell#774] opened 2023-08-31 02:04 UTC
Have Windows 11 and while installing it looks for short-cuts and can't find them then asks me to delete or keep and this continues for quite awhile, and I had to terminate the install only to have my desktop completely wiped out... Please advise, thank you.

**Comment by dremin** [comment] 2023-08-31 03:01
I'm not entirely certain what you are referring to, could you please provide a screenshot?

**Comment by BigT2013** [comment] 2023-08-31 04:13
I've uninstalled it and don't have it available for screen-shot. I don't want to try to install it again without knowing what is happening. It kept looking for shortcuts to software and not finding them, then it would ask if I wanted to delete it. It left my taskbar hidden and I lost all my desktop icons. It seems the icons were turned off, so I did manage to get them back. It appeared to me it deleting software shortcuts when it couldn't find them. Some kind of glitch. I'm running Windows 11 fully updated. 
Please explain. If there is a log file someplace, let me know. Thanks

**Comment by dremin** [comment] 2023-08-31 04:16
There is a log, it would be great if you could upload it. Open a file explorer window to `%localappdata%\Cairo_Development_Team\Logs` and the log files should be there!

**Comment by BigT2013** [comment] 2023-08-31 14:37
Ok, I found it. Here is user.config and log file. 
[08-30-2023.log](https://github.com/cairoshell/cairoshell/files/12487178/08-30-2023.log)
[user.zip](https://github.com/cairoshell/cairoshell/files/12487182/user.zip)
Let me know if you discover anything. The log file doesn't seem to contain much. Thanks again.

**Comment by markbrents** [comment] 2023-10-10 00:48
I just installed Cairo on Windows 10 and had a similar experience. It appears that I had several shortcuts to applications that no longer exists on my machine (I assumed). According to the log it was looking for "Adobe Photoshop 2021.lnk". I believe Photoshop changed folders when it updated itself to 2024 because I do have a link on my system called "Adobe Photoshop 2024.lnk"
[10-09-2023.log](https://github.com/cairoshell/cairoshell/files/12851567/10-09-2023.log)

**Comment by dremin** [comment] 2023-10-16 04:50
Thanks for all of the details, I've been able to reproduce this and will have a fix.

**Comment by dremin** [comment] 2024-05-25 17:30
This is now fixed in the latest release.

**Closed by dremin** 2024-05-25 17:30 UTC
