### ISSUE TITLE
Autohide Cairo menu bar.

### ISSUE THREAD

**Issue by jakkaas** [cairoshell/cairoshell#267] opened 2019-06-01 04:56 UTC
**Is your feature request related to a problem? Please describe.**
While scrolling using a precision synaptic touchpad, the Cairo menu bar is observed to be flickered. Also, some app does not properly align under Cairo menu bar.

![image](https://user-images.githubusercontent.com/43289832/58743858-3ce25d80-8457-11e9-912b-7ab8651ed64b.png)
Image chromium edge dev mode.

**Describe the solution you'd like**
Autohide Cairo menubar could solve the above problem

Thanks

**Comment by rcnza** [comment] 2020-02-25 09:55
+1 for being able to hide the menubar

**Comment by dremin** [comment] 2020-04-08 01:29
Is the issue causing the overlap resolved now? I cannot reproduce.

For auto hide menu bar, that will be covered under #120.

**Comment by jakkaas** [comment] 2020-05-20 09:02
The flickering and overlapping issue is resolved. thanks

**Comment by dremin** [comment] 2020-08-21 04:16
Closing as duplicate of #120

**Closed by dremin** 2020-08-21 04:16 UTC
