### ISSUE TITLE
Language bar does not appear in the Cairo tray

### ISSUE THREAD

**Issue by vladkorotnev** [cairoshell/cairoshell#237] opened 2019-02-10 03:40 UTC
**Describe the bug**
Not sure how I didn't notice this all the time I'm using Cairo, but there was that one day I got a new keyboard and was unsure on how to switch from Kana to English on it... and realized I don't have an option to switch it from the menu either because the keyboard language bar doesn't appear.

The fact that in Win10 the language bar is not a separate component and cannot be detached, but is rather a UWP addon of sorts, does not help.

**Steps to reproduce**
1. Have more than one keyboard language installed, or an IME such as Japanese input
2. Try to switch language/mode using the regular tray icon
3. ... but there is no icon

**Expected behavior**
Language bar and IME options would appear alongside the tray icons.

**System information:**
- Windows version: Windows 10 version 1803 build 17134.345
- Cairo version: 0.3.6746.0 - Pre-release
- 32-bit or 64-bit: 64
- In Cairo Settings > Advanced, is Cairo set as shell?: yes

**Comment by josuave** [comment] 2019-02-10 12:30
This is the same as Issue #212. I have done some work changing the windows input language but, as far as I have gotten in research, the windows API does not provide a way of gettin the inputs shortened name(as shown on the input bars icon. This may be handled by the language bar itself.

**Comment by dremin** [comment] 2020-01-21 00:37
Closing as duplicate of #212.

**Closed by dremin** 2020-01-21 00:37 UTC
