### ISSUE TITLE
please make it possible to create or modify folders in "Places" section

### ISSUE THREAD

**Issue by ivan8994** [cairoshell/cairoshell#798] opened 2024-04-22 02:44 UTC
by default, user can find Docs, Downloads, Pictures, Music etc.

would be great to be able to modify this list, for example option to remove "Videos" folder or add own folder with personal name, for example "Work" or "Projects" or whatever.
I found there is an [extention](https://github.com/cairoshell/CairoExtensionSamples#placesshellfolders) "Places.ShellFolders" but as a ordinary user I have no idea how to properly install it, but I tried and failed, and even though the procces is too way complicated as for such a general action.

can you please improve or make it easier for ordinary customer ?

**Comment by dremin** [comment] 2024-06-14 06:18
Duplicate of #92. I am working towards making this customizable in the UI.

**Closed by dremin** 2024-06-14 06:18 UTC
