### ISSUE TITLE
Cairo sees only a half of screen

### ISSUE THREAD

**Issue by batareya16** [cairoshell/cairoshell#93] opened 2018-02-22 14:32 UTC
![screenshot](https://user-images.githubusercontent.com/24940733/36543703-9b919bf4-17f5-11e8-915f-2236f5bdd5dd.png)

after restarting Сairo, when I want to change theme, Cairo sees only half of the screen, the second ignores until I reboot the system.

**Comment by mdmk** [comment] 2018-02-22 18:21
What is your OS ?
Version of Windows and architecture (32 or 64bit) ?
You can check this via Win+Pause on your keyboard or right click > properties on 'My PC' icon on desktop or file explorer.

Please test if the issue persists without sysinternals virtual desktop running.
Does the issue appear on desktop itself or via TeamViewer ?

**Comment by mdmk** [comment] 2018-02-22 23:09
You don't have the latest build ?
I notice the desktop button is missing on the taskbar.

**Comment by dremin** [comment] 2018-02-22 23:25
@batareya16 Thanks for the report! In addition to the items requested by @mdmk, when you installed Cairo did you select the option 'run at startup', or 'Advanced users only: Replace Explorer'?
Also, does this happen every time you restart Cairo without rebooting, or only sometimes?

@mdmk - one possibility for the missing Desktop icon is that they disabled Cairo's desktop icons.

**Comment by mdmk** [comment] 2018-02-23 00:01
@dremin
I meant [Dynamic Desktop Overlay button](https://user-images.githubusercontent.com/7373633/35663390-041144fc-06eb-11e8-844c-a3834ab4b484.png)
Implémented in #45

**Comment by dremin** [comment] 2018-02-27 06:25
I reproduced something that looks like this. It happens if Cairo is set as user shell, and Cairo is restarted after screen res or display changed while Cairo was open. That should be fixed in the next build.

**Comment by dremin** [comment] 2018-03-02 02:29
This has been fixed in the latest release.

**Closed by dremin** 2018-03-02 02:29 UTC
Labels: Bug
