### ISSUE TITLE
Settings App not starting when Cairo is set as Shell

### ISSUE THREAD

**Issue by paleiadevelopment** [cairoshell/cairoshell#521] opened 2021-01-16 11:31 UTC
**Describe the bug**
When Cairo is set as the shell, Windows' Settings do not start, nor do any Apps that iuse UWP/Modern UI (like Store, XBox, Calculator...)

**Steps to reproduce**
1. have Cairo set as the Shell and restart
2. try to start any UPW app
3. observe it not starting :)

**Expected behavior**
All UWP/Modern UI apps should still start if Cairo is set as the Shell

**System information:**
 - Windows version: Win 10 Pro 20H2
 - Cairo version: 0.3.7174
 - 32-bit or 64-bit: 64bit
 - In Cairo Settings > Advanced, is Cairo set as shell?: Yes

**Additional context**
The issue this causes is that large portions of the system settings are inaccessible, as they have been moved by MS to the Settings app.
It also makes it impossible to set individual wallpapers; Cairo's own Settings only allow to Tile a single wallpaper across all screens, not so set individual wallpapers per screen (I have 5).

**Comment by dremin** [comment] 2021-02-04 03:53
Thanks for the report! Unfortunately, alternate shells are not currently able to activate UWP apps such as Settings without Explorer running. We recommend running Cairo on top of Explorer when using Windows 10.

I believe this is a duplicate of #365 and am closing as such.

**Closed by dremin** 2021-02-04 03:53 UTC
