### ISSUE TITLE
[Bug] Alt-Tab doesn't work

### ISSUE THREAD

**Issue by Gentle888** [cairoshell/cairoshell#136] opened 2018-04-16 21:01 UTC

**Comment by dremin** [comment] 2018-04-17 02:36
I'm unable to reproduce this, alt-tab always works for me with Cairo open. Do you have steps I can follow to reproduce?

**Comment by dremin** [comment] 2018-07-03 23:49
Closing due to lack of reproduction

**Closed by dremin** 2018-07-03 23:49 UTC
