### ISSUE TITLE
Border name cannot be found in the name scope of ...

### ISSUE THREAD

**Issue by DoerrSt** [cairoshell/cairoshell#167] opened 2018-07-06 09:32 UTC
I recevied the error "Border name cannot be found in the name scope of ..." several times today. Screenshot of the complete message is attached. 

Unfortunately, I don't see a way to reproduce this.  

 - Windows version:  Windows 7 Pro
 - Cairo version: 0.3.6680.0 Pre-release, 64-bit 
 - In Cairo Settings > Advanced, is Cairo set as shell?:   No
![cairo desktop error](https://user-images.githubusercontent.com/115788/42371588-31463492-8110-11e8-9661-d764be6f29a6.png)

**Comment by josuave** [comment] 2018-07-06 16:24
Check the install folder and make sure the xaml theme files are there

Sent from my iPhone

On Jul 6, 2018, at 5:32 AM, DoerrSt <notifications@github.com<mailto:notifications@github.com>> wrote:


I recevied the error "Border name cannot be found in the name scope of ..." several times today. Screenshot of the complete message is attached.

Unfortunately, I don't see a way to reproduce this.

  *   Windows version: Windows 7 Pro
  *   Cairo version: 0.3.6680.0 Pre-release, 64-bit
  *   In Cairo Settings > Advanced, is Cairo set as shell?: No
[cairo desktop error]<https://nam01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F115788%2F42371588-31463492-8110-11e8-9661-d764be6f29a6.png&data=02%7C01%7C%7C7b2fbdf097c1429d853708d5e3236523%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636664663509405962&sdata=Hxuth40wlFoVhusB21QtlBu3NdFkF7kdykj7gRjY6Zo%3D&reserved=0>

**Comment by dremin** [comment] 2018-08-07 04:35
I've seen this before but haven't been able to reproduce.. seems to be an issue with a taskbar button animation.

**Comment by dremin** [comment] 2020-02-02 20:45
This should be fixed now.

**Closed by dremin** 2020-02-02 20:45 UTC
