### ISSUE TITLE
Notification tray (Systray.exe) and "Quick start" or Pinned apps not loading properly

### ISSUE THREAD

**Issue by FiddleStickers** [cairoshell/cairoshell#29] opened 2017-10-04 22:37 UTC
Funny thing is that it does show the steam icon, but none of the others. (I chose to use explorer.exe as my default when I installed, because it told me that some windows features would otherwise not be available)
Also, I did set it to always show all tray icons in the settings.
I have Windows 10 x64 =)

![cairoshell-bugmaybe](https://user-images.githubusercontent.com/32528471/31203149-15ab49c0-a966-11e7-8b3e-506b84975314.png)

**Comment by dremin** [comment] 2017-10-04 23:33
For the icons in the taskbar, you can select those in the App Grabber and placing them in the Quick Launch category (at the moment, Cairo does not select these automatically when installing). Regarding the notification area, did you make sure to install the 64-bit version of Cairo?

**Comment by FiddleStickers** [comment] 2017-10-04 23:36
Okay then I will set the quick launch up myself.
Yes I installed the 64bit version.

**Comment by mdmk** [comment] 2017-10-05 15:25
OS: Windows 10 x64
Cairo Desktop version: M2.6469 x64

Same problem here (cf. screenshot attached).
There is two icons that do not load in the cairo tray (red circles) but appear on explorer taskbar.
A third icon disappears during screenshot because that is the screenshot tool, not a real problem here, it instantly reloads.

I did clear MUI cache and reboot, no effect.

I do not have problems with quick lauch icons, but it would be cool to load the same than in explorer.
That is, the shortcuts in:
`%AppData%\Microsoft\Internet Explorer\Quick Launch\User Pinned\TaskBar`
May I open an issue for such feature request?

![screenshot12](https://user-images.githubusercontent.com/32496803/31235468-e76fc70c-a9f1-11e7-835e-adcb96dca808.png)

**Comment by dremin** [comment] 2017-10-06 21:45
@FiddleStickers does the issue persist after logging out and back in?

@mdmk Could you please let me know what apps these are so I can investigate? Are they running under another user by chance?

Also, I am planning on auto-selecting apps in a future Cairo release (the first Milestone 3 build should have this feature). Please feel free to open a separate issue for this, and I can keep it updated once the feature is available.

**Comment by FiddleStickers** [comment] 2017-10-07 00:58
To be clear, my only issue right now is the notification tray icons missing.
I assumed Cairo would load my pinned apps from explorer, but it does not (Which is fine).

I am now going to test logging out and back in to see if that fixes the tray icons.

**Comment by FiddleStickers** [comment] 2017-10-07 01:01
Yes. The issue persists.

**Comment by mdmk** [comment] 2017-10-07 14:35
@dremin The apps are Asus Xonar DGX panel (sound card) and Logitech Options (keyboard and mouse buttons and macro and hybrid software/hardware KVM).
If you have at least one Logitech keyboard or mouse with unifiying dongle you can test the later.
I run everything as a single admin user.

I did open Feature resquest #31 for auto-select apps feature.

**Comment by dremin** [comment] 2017-10-07 22:28
@FiddleStickers - darn, I will look some more into this. Could you please provide a screenshot of your normal taskbar notification area so that I can see what icons you are expecting?

@mdmk Thanks, I'll take a look at these.

**Comment by FiddleStickers** [comment] 2017-10-07 23:09
I will. I am restarting my pc now, but I can say that among the missing icons are logitech mouse settings for meas well.

**Comment by FiddleStickers** [comment] 2017-10-07 23:13
Sorry missclick. Screenshot incoming

**Comment by FiddleStickers** [comment] 2017-10-07 23:16
Also when I switch back to windows explorer shell it leaves the minimize and maximize window animation.

I hope you can get it to set that back to default, because I can't get rid of it haha.

**Comment by FiddleStickers** [comment] 2017-10-07 23:21
![notification_icons](https://user-images.githubusercontent.com/32528471/31312570-f8379250-abc6-11e7-8202-515f6887a1f1.png)

Here are all the icons that are missing.

**Comment by mdmk** [comment] 2017-10-08 18:09
@dremin I noticed that at the very moment I switch off my logitech mouse, the logitech options icon finally appear on cairo tray. But if I close and reopen Cairo, it is gone again.

The logitech options software that @FiddleStickers uses is perhaps not the same than mine, in his case it is a gamer mouse of keyboard, I guess it from the G icon that is used by logitech for its gaming peripherals.

**Comment by nickisghosty** [comment] 2017-10-09 02:05
i just noticed, my wifi icon isnt in the sys tray. nor is my volume icon will try a restart and see if it fixes it

**Comment by FiddleStickers** [comment] 2017-10-12 11:50
I only have wired mouse and keyboard, because I hate batteries =P

**Comment by mdmk** [comment] 2017-10-12 13:20
@FiddleStickers I understand ^^
Unplugging and replugging the dongle does also make the icon reappear.
Did you try to unplug the cord?

**Comment by dremin** [comment] 2017-10-13 03:07
I installed the Logitech software and can't seem to reproduce the issue.. it always is appearing in Cairo for me. 🤷‍♂️

**Comment by mdmk** [comment] 2017-10-13 15:48
@dremin In my case I only have an icon when logitech flow is enabled (it is a hybrid software/hardware kvm).
The icon appears in explorer native taskbar when flow is enabled and the unifiying dongle is plugged.
In Cairo the icon appear only when flow triggers an event.
eg my mouse switches to the other pc screen, or the other pc shut down.
What are your logitech peripherals?

**Comment by dremin** [comment] 2017-10-13 22:00
@mdmk I have a G400 mouse. The Logitech Gaming Software icon was present in my notification area in Cairo across restarts of Cairo without an issue in my case.

The big issue with notification area icons is that there is no API to enumerate them, rather, I have to trust that each icon will tell Cairo about its presence when Cairo announces that it has a notification area. Unfortunately it seems like a lot of apps don't implement this correctly or only announce to Explorer.

**Comment by mdmk** [comment] 2017-10-14 00:15
@dremin So same icon than @FiddleStickers
Not the same than me.
Is there a way to help you look at this, even if you don't have direct access to the app?

For the use case where explorer is replaced by Cairo, is there a way to make Cairo impersonate explorer so it gathers the same information as explorer would?

**Comment by dremin** [comment] 2017-10-23 00:24
@mdmk Every app's implementation is different-- Cairo is behaving as closely as possible to Explorer, though running Cairo as a replacement to Explorer (using the installer option) would get that a bit closer. The most helpful thing would be to run the [DebugView](https://docs.microsoft.com/en-us/sysinternals/downloads/debugview) application, then start Cairo, and send the output. That can tell me if the issue lies within Cairo or the app not sending Cairo its icon.

**Comment by dremin** [comment] 2017-11-28 05:41
The "pinned apps" issue is fixed in the latest Milestone 3 release.

**Comment by mdmk** [comment] 2017-11-28 17:33
@dremin 
Two logs
[Here](https://gist.github.com/mdmk/af7799b41d5e9e5dd29c3069466e98ca) I run Cairo just afer debugview, and the logitech option icon does not appear.
[There](https://gist.github.com/mdmk/6d4747e8297fcaf7208ca4f2b03419cb) I run Cairo just after debugview, just as before, and switch my wireless mouse off and on in order to force the icon to show.
Please let me know if you need any other information.

**Comment by mdmk** [comment] 2017-11-28 17:35
[CoreTemp](http://www.alcpu.com/CoreTemp/) tray icon does not work (placeholder black squares instead of temperature counters).

**Comment by dremin** [comment] 2017-11-29 00:46
@mdmk Thanks for the logs, they help a lot. Unfortunately it almost looks to me like it may be a bug in Logitech Options. When the taskbar created message is sent, other applications respond with their icons correctly every time it is sent. Logitech Options only sends a message once you toggled your mouse off/on. To help narrow this down, could you try (with Cairo closed) restarting all explorer.exe processes and see if the Logitech Options icon is present without toggling your mouse off and on?

**Comment by mdmk** [comment] 2017-11-29 10:43
@dremin When restarting explorer process, Logitech Options does not reappear, even with toggling off and on. But if I unplug and replug the dongle, then hover the tray notification zone with mouse cursor, icon will reappear.
[Here](https://gist.github.com/mdmk/7484167a287702e3bd02dd11ada3294b) a log using this method.
Looks really like a bug in the app itself as you said. Thanks for investigating this.

**Comment by dremin** [comment] 2017-12-01 05:49
@mdmk I was able to reproduce the Core Temp issue, and it will be fixed in the next build.

**Comment by dremin** [comment] 2017-12-13 04:33
@FiddleStickers is your issue still occurring?

**Comment by dremin** [comment] 2018-01-01 23:37
Closing due to lack of further reproduction.. feel free to provide more details if you have any. Thanks!

**Closed by dremin** 2018-01-01 23:37 UTC
Labels: Bug

**Comment by lordgog** [comment] 2019-06-14 14:51
We noticed a similar issues where none of the system tray/notification area icons would appear when debugging from Visual Studio. However, the installed version worked just fine. Turns out Visual Studio was running in administrator mode, and started Cairo as an administrator too. When run like normal, ie. in the user's name, the icons worked fine.
