### ISSUE TITLE
Drag & Drop

### ISSUE THREAD

**Issue by XorogVEVO** [cairoshell/cairoshell#323] opened 2020-01-27 19:44 UTC
**Is your feature request related to a problem? Please describe.**
I like this desktop environment but it's really frustrating to actually use the built-in desktop because there's no drag & drop. Of course there's still the Cut Feature but that's just not always the option.

**Describe the solution you'd like**
Add Drag & Drop.

**Describe alternatives you've considered**
/

**Additional context**
/

**Comment by josuave** [comment] 2020-01-27 22:05
I agree this should get some attention at some point.

**Comment by dremin** [comment] 2020-02-02 01:08
Closing as duplicate of #85

**Closed by dremin** 2020-02-02 01:08 UTC
Labels: Feature Request
