### ISSUE TITLE
Cairo 0.3.6701.0 crash

### ISSUE THREAD

**Issue by ch3wt0ys** [cairoshell/cairoshell#186] opened 2018-08-20 16:08 UTC
Was just watching Youtube videos through Firefox and whole desktop froze for a minute and tossed up an error. Couldn't take a screenshot or open taskmanager through ctrl-shift-esc, ctrl-alt-delete did not work either. Took a photo with my phone and found the log for Cairo to post here. Clicked 'yes' to restart Cairo and it did not restart the shell, had to do so manually.

 - Windows version: Windows 10 Enterprise
 - Cairo version: 0.3.6701.0
 - 32-bit or 64-bit: 64-bit
 - In Cairo Settings > Advanced, is Cairo set as shell?: Yes

Log is at bottom of post.

![cairoerror](https://user-images.githubusercontent.com/42548120/44352174-a4539180-a471-11e8-9dfb-7812677c2d9c.png)
[08-20-2018-Backup.log](https://github.com/cairoshell/cairoshell/files/2303093/08-20-2018-Backup.log)

**Comment by dremin** [comment] 2018-08-28 01:52
This tends to happen when there is a handle leak somewhere on the system. Are you able to reproduce this consistently? If so, a screenshot of Task Manager with the "Handles" column selected with Cairo present in the screenshot will help isolate if it is a Cairo issue or not.

**Comment by tmajibon** [comment] 2018-12-30 03:09
Found this issue listing, been having the same error in the most recent version.

![capture](https://user-images.githubusercontent.com/5880760/50544022-e2925780-0bad-11e9-8469-d95965c9e8df.PNG)

**Comment by dremin** [comment] 2019-12-26 04:06
The issue appears to be WPF choking due to an app on the system which is not Cairo leaking handles. Closing this as a result.

**Closed by dremin** 2019-12-26 04:06 UTC
