### ISSUE TITLE
please make it possible to hide Menu Bar 

### ISSUE THREAD

**Issue by ivan8994** [cairoshell/cairoshell#780] opened 2023-11-21 19:10 UTC
**Describe the solution you'd like**
Since most Windows laptops feature 16:9 display, there is no extra space (comparing to Mac 16:10 display) that can be easily sacrificed for Menu Bar. This makes a constant visible Manu Bar **a super frustrating thing.**  
Could you **_please_** add a feature into settings to adjust Manu Bar position just as in Cairo Shell the Task Bar already can be changed to **auto-hide**

Also, it would be nice to add 2-3 different delay options : _instant_, _1 sec, 2 sec,_ because as Mac user I may confirm when you work with Web Browser and want to change the Tab, you hover the mouse at the top of the screen and Menu Bar apperas every time, it bothers. 1-2 secs delay could easily solve this issue

**Comment by pyrareae** [comment] 2023-11-25 03:08
As a long-time KDE/Plasma user who's been using Windows again recently and is used to being able to customize the desktop shell quite a bit, I've been giving Cairo a shot to try and fix some of my grievances with the stock Explorer shell. It definitely bugs me that I cannot hide the top bar as I don't want a bar just for a systray and some folder shortcuts eating screen real estate. This is compounded by the fact that the taskbar can be hidden, so why not the menu bar as well?

**Comment by dremin** [comment] 2023-11-28 05:38
Thanks for the feedback! I am currently working on adding this feature in #120. Closing this as a duplicate of #120.

**Closed by dremin** 2023-11-28 05:38 UTC
