### ISSUE TITLE
[important] CairoShell incorrectly shows opened programs on TaskBar when working with Virtual Desktops

### ISSUE THREAD

**Issue by ivan8994** [cairoshell/cairoshell#800] opened 2024-04-24 16:55 UTC
Windows 10 22H2
let's say you have several Virtual Desktops (**_VD_**) opened (those visible by pressing Windows+Tab) , and have different apps opened on different Virtual Desktops

**_the problem :_** 
- TaskBar settings : **show lables**
- you have several _**VD**_ created with various windows opened. on **_VD 1_** there is Word opened and Music Player opened, on **_VD 2_** there is Notepad and File Explorer opened, on **_VD 3_** there is Chrome opened, on **_VD 4_** there is 2 Chrome windows opened

- **expected behaviour :**

**_scenario 1)_** if you switching between several created Virtual Desktops, only programs opened on current Virtual Desktop are visible on TaskBar of the current Virtual Desktop
**_scenario 2)_** if you switching between several created Virtual Desktops, all opened windows of all launched apps are visible on TaskBar , no matter which exactly Virtual Desktop you currently selected

- **actual current behaviour :**
when switching between various created **_VD_**, labels of opened programs are shown in random order, the number of visible opened apps constantly changes, sometimes TaskBar of _**VD 3**_ has also windows from **_VD 1_** , sometimes when switching from **_VD 1_** to **_VD 2_** the TaskBar has the correct list of windows opened only on **_VD 2_**, but if switching next to  **_VD 3_** the TaskBar still has windows opened from **_VD 2_**, and so on and so on in similar manner 

**_TESTED_** : 
the issue has nothing common with **default W10 settings** of showing _**specific opened apps**_ on Default Taskbar of the **_current specific Virtual Desktop_** , or show **_all_** opened apps on Default Taskbar on **_all_** Virtual Desktops (those settings can be found in **_W10 Settings > General > Multitasking_**)
this issue tested in both modes of W10 Settings, problem exists the same, **no dependence found**

**_example 1_**

![cairo 01](https://github.com/cairoshell/cairoshell/assets/75372078/582f8763-b8f8-4960-b875-d2a6435e4e70)
![cairo 02](https://github.com/cairoshell/cairoshell/assets/75372078/f0c795ff-cbc3-4eb8-aea0-dc4812acb0f4)
![cairo 03](https://github.com/cairoshell/cairoshell/assets/75372078/e527a647-67a4-4920-8bc6-1c67641586ba)
![cairo 04](https://github.com/cairoshell/cairoshell/assets/75372078/d9f28029-dbd6-48a9-a03b-ee6d18ee318f)
![cairo 05](https://github.com/cairoshell/cairoshell/assets/75372078/dd3e25b1-8b91-42bf-b043-99ee81d1c9fb)

**_example 2_**

![cairo alt 01](https://github.com/cairoshell/cairoshell/assets/75372078/7ac2b595-2c18-4f1b-aa04-5e6e65c96b05)
![cairo alt 02](https://github.com/cairoshell/cairoshell/assets/75372078/8475911b-a44e-4937-a6c8-5db162b8c4eb)

**Comment by dremin** [comment] 2024-12-02 01:38
Closing as duplicate of #398, which I have a fix coming for.

**Closed by dremin** 2024-12-02 01:38 UTC
