### ISSUE TITLE
Cairo menubar flickering during scrolling using the synaptic precision touchpad.

### ISSUE THREAD

**Issue by jakkaas** [cairoshell/cairoshell#264] opened 2019-05-30 01:45 UTC
**Describe the bug**

Both the Cairo menu and taskbar flicker while scrolling any app/explorer using the synaptic precision touchpad. The flickering does not happen while using the mouse for scrolling.

**System information:**
 - Windows version: 1903
 - Cairo version: 0.3.6768.0
 - 32-bit or 64-bit:  64 bit
 - In Cairo Settings > Advanced, is Cairo set as shell?: No

**Comment by dremin** [comment] 2020-08-21 03:56
Closing, we have been unable to reproduce this issue.

**Closed by dremin** 2020-08-21 03:56 UTC
