### ISSUE TITLE
Pin to Quick Launch in Context Menu

### ISSUE THREAD

**Issue by Mehere888** [cairoshell/cairoshell#271] opened 2019-06-22 14:43 UTC
The fastest way I know of adding a program to Quick Launch is by first dragging it to Programs, and then right-clicking on it to be added into Quick Launch.

Unless I'm missing something, consider adding "Pin to Quick Launch" in the Context Menu, just like I can normally "Pin to Start" or "Pin to Taskbar".

**Comment by josuave** [comment] 2019-06-22 15:04
This is a duplicate of issue #262.
I have code in my fork that resolves this to an extent.
Feel free to download and build the fork to get the feature before its merged

**Comment by Mehere888** [comment] 2019-06-22 16:36
Thanks. Sorry I tried to search make sure it wasn't a duplicate.

I don't know how to apply your suggestion. My skills are about as good 
as double-clicking on an .exe in windows, haha.

I can do without, just thought it'd be nice to have.

**Comment by josuave** [comment] 2019-06-23 01:16
That’s OK. My code changes Will be included with the main project at some point in the future. Just needs to go through an approval process. The basic idea is you  right click the icon for the running process and be able to pin it to the quick lunch.

**Comment by dremin** [comment] 2019-11-24 04:10
This is now available in the latest release.

**Closed by dremin** 2019-11-24 04:10 UTC
